nav:
  - index.md
  - Grundschritt.md
  - Tor.md
  - Schmetterling.md
  - Körbchen.md
  - Brezel.md
  - Swing out Swing in.md
  - Macho.md
  - Fenster.md
  - Taucher.md
  - Tunnel mit Flirt.md
  - Sweetheart Schiebetür.md
  - Klappmesser.md
  - 6er Schritt.md
  - He goes She goes.md
  - Wings.md
  - ...
