nav:
  - Grundschritt.md
  - Kreisel.md
  - Chasse.md
  - Kreuzschritt.md
  - Schaufel.md
  - Flugschritt.md
  - Doppeltes Lottchen.md
  - Twinkle Step.md
  - In and Out.md
  - Woodpecker.md
  - Quick Change.md
  - ...
