nav:
  - Grundschritt.md
  - Damensolo.md
  - Promenade.md
  - Hand zu Hand.md
  - Spot-Turn.md
  - Shoulder to Shoulder.md
  - Eisenbahn.md
  - Umgreifen.md
  - Handtuch.md
  - Sweetheart.md
  - Zig Zag Ronde.md
  - Puppenspieler.md
  - Caress.md
  - Spotturn Caress.md
  - Fan.md
  - Spaziergang.md
  - Rechts Links Körbchen.md
  - Looping.md
  - Walks into Cuban Break.md
  - ...
