nav:
  - Grundschritt.md
  - Damensolo.md
  - Promenade.md
  - Hand zu Hand.md
  - Spot-Turn.md
  - Shoulder to Shoulder.md
  - Lasso.md
  - Aida.md
  - Zig Zag Ronde.md
  - Handtuch.md
  - Sweetheart.md
  - Caress.md
  - Spotturn Caress.md
  - Copperfield.md
  - Fan.md
  - Spaziergang.md
  - Pfau zum Geigenhals.md
  - ...
