nav:
  - Grundschritt.md
  - Flirt.md
  - Damensolo.md
  - Platzwechsel.md
  - Kicks.md
  - Stop and Go.md
  - American Spin.md
  - Box.md
  - Twist and Swivel.md
  - Kicks mit bump.md
  - Fallaway throwaway.md
  - Bretzelfolge.md
  - Kicks drehung.md
  - ...
