nav:
  - Grundschritt.md
  - Kreisel.md
  - Linksdrehung.md
  - Promenade.md
  - Valentino.md
  - Rudolpho.md
  - 5er Schritt.md
  - Doppelkehre.md
  - Offene Promenade Wiege Kehre.md
  - 3 Wischer.md
  - ...
